### ISSUE TITLE
Docblocks and stricter types

### ISSUE THREAD

**Issue by kitbs** [dillingham/stubs#22]
Hi @dillingham 

I have been itching to add some docblocks and argument/return types throughout, but don't want to overstep. What do you think?

**Comment by dillingham** [comment]
@kitbs Honestly Im completely open to it, just have never used them lol

Is there an official guide? Im happy to brush up
All I found was this: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md

**Comment by kitbs** [comment]
Cool. I think they're really valuable, especially for the public API, because they help with IDE autocompleting.

The link you found looks like an intimidating spec, but there's a friendlier guide at https://docs.phpdoc.org/getting-started/your-first-set-of-documentation.html

They don't have to be too much of a chore, either. There'll probably be a plugin for whatever IDE you use that helps you by stubbing (😆) the docblock from what it can infer from each method. You just have to fill in the description, @param and @return types. The Atom plugin (Serenata) I use also shows lint errors if I haven't added a docblock or the docblock is inconsistent with the actual function.

In [VariableSet.php](https://github.com/kitbs/stubs/blob/97eaffdfaf5d20394957b2557cfedc9ffcb44bed/src/VariableSet.php) in my last PR you can see some in action.

**Comment by dillingham** [comment]
Thanks for the reference! Not as scary as they look lol
I added them to all the properties & methods.
Im not very opinionated on how the messages read.
Feel free to correct me if you catch something

Thanks again!
